name: Mirror to Public Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to public repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git rm -r .github/workflows/
          git commit --amend --no-edit
          git remote add public https://x-access-token:${{ secrets.DOYLIB_BASE_TOKEN }}@github.com/DO-YAC/doylib.base.git
          git push public main --force
